### ISSUE TITLE
Hardcoded tempfile names -> security vulnerabilities

### ISSUE THREAD

**Issue by charles-dyfis-net** [niieani/bash-oo-framework#1]
Use of hardcoded names referring to world-writable locations, ie. `/tmp/stored_exception`, mean that an attacker can create symlinks to a file they don't themselves have write privileges to in such a location, and rely on separate program using the infinity framework to overwrite that symlink's target.

(See also concurrency issues).

**Comment by niieani** [comment]
I am aware of the problem and that this is a less-than-perfect workaround. However, I have not found any better way of getting variables out of a subshell. Do you have any better ideas?

Concurrency issue would be fixable by adding a $PID in front of the name. We could also use a location relative to the library, that won't fix the vulnerability in full, though.

Thanks for participating!

**Comment by charles-dyfis-net** [comment]
mktemp -- creating destinations guaranteed to be unique and to which no other user can write -- is the canonical best practice.

**Comment by niieani** [comment]
That might work. Though the file would have to be created preemptively, otherwise we'd have the same problem with getting it's filename.

**Comment by charles-dyfis-net** [comment]
Yup. Using an exit trap would make eager creation less awful from a cleanup perspective.

**Comment by niieani** [comment]
Fixed in https://github.com/niieani/bash-oo-framework/commit/d555fe28d558463b2586576be8681c463b537bea.
