### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by insign** [niieani/bash-oo-framework#101]
Hi, before use and maybe invest some time to make the project better I usually ask if the project is active. I mean, if it is being reviewed by the mantainers.

P.S: The reason of this issue, is the long time since last commit/merge.

**Comment by niieani** [comment]
hey @insign! The project isn't dead, but there isn't much active development happening at the moment. I'm still accepting and reviewing PRs. There's a [discussion](https://github.com/niieani/bash-oo-framework/discussions/91) around version 3.0, which would be a complete rewrite, and with some great ideas, but so far we don't have the man-power/time to invest in developing it.

If someone wants to take on that effort, I'm still happy to review/discuss the direction and if we're aligned, make that person a contributor to the project, with all due credit.

**Comment by insign** [comment]
I'm not sure if I am the one. But how can I help reviewing PR?

PS: I'll read now the mentioned discussion.

**Comment by niieani** [comment]
Feel free to review PRs, should any come, any help is appreciated!
