### ISSUE TITLE
Sorry, a bit cheeky/impolite...

### ISSUE THREAD

**Issue by SeanScherer** [niieani/bash-oo-framework#105]
But I'm trying to find a different project (that has at least a slight overlap with yours), and I thought maybe you might happen to know it:

Its a framework for setting up a projects dependencies / running the build command, or giving other info that normally would reside in a readme file. (the authors chose bash for it due its universal availability).

I'd seen this some time ago, and do what I want, can't find it right now anymore. So asking here is grasping for straws out of frustration, apologies that its absolutely off-topic to your actual repository :/ .

Thanks for your time anyway, and regards!
Sean

P.S. I was desperate enough to [ask on Stackoverflow](https://stackoverflow.com/questions/74804572/bash-project-that-serves-both-as-readme-will-setup-a-projects-environment) as well...

**Comment by niieani** [comment]
Sorry, I don't know the one. Try asking ChatGPT.

**Comment by SeanScherer** [comment]
Thats an idea at least I guess :).

Thanks anyway!

Edit: If I do end up doing a little more with Bash, I'll be giving this project a look :) !
