### ISSUE TITLE
Exits and closes the shell window when the test scripts executed

### ISSUE THREAD

**Issue by matara68** [niieani/bash-oo-framework#12]
I tried executing a couple of test scripts (try-catch.sh and oo.sh). The shell window was immediately closed when executed.

My bash version is as follows.
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.

Please give me some guide lines on solving this.

Thanks.

**Comment by niieani** [comment]
Hi @matara68.
Unfortunately the framework doesn't support bash 3 yet (see https://github.com/niieani/bash-oo-framework/issues/3). 
Try upgrading to bash 4.
