### ISSUE TITLE
Terminal not restored on cygwin

### ISSUE THREAD

**Issue by digulla** [niieani/bash-oo-framework#4]
The error handling framework shows the error on Cygwin (some characters look odd, though) and then offers to exit or continue.

When I press Ctrl+C to exit, I get a new prompt but the terminal is in a bad state - I can't see what I type anymore. I have to blindly type "stty sane" to reset the terminal.

I'm not sure why that happens. I tried `read -s` in the terminal and aborted it with Ctrl+C. The editing was restored in this case, so it must be something else. The escape codes in line 232 of https://github.com/niieani/bash-oo-framework/blob/master/lib/system/03_exception.sh (c282937515e113ceb0ff3aa986a2f2129884f279) also doesn't look like it's leaking something.

Maybe a trap handler?

I'm using a recent version of Cygwin with BASH 4.3.42.

**Comment by digulla** [comment]
Workaround: Add

    trap "stty sane; exit 1" INT

in line 231. The code block now reads:

    if [ -t 0 ]
    then
        trap "stty sane; exit 1" INT
        Console.WriteStdErr
        Console.WriteStdErr " $(UI.Color.Yellow)$(UI.Powerline.Lightning)$(UI.Color.White) Press $(UI.Color.Bold)[CTRL+C]$(UI.Color.White) to exit or $(UI.Color.Bold)[Return]$(UI.Color.White) to continue execution."
        read -s
        Console.WriteStdErr " $(UI.Color.Blue)$(UI.Powerline.Cog)$(UI.Color.White) Continuing...$(UI.Color.Default)"
        return 0

**Comment by niieani** [comment]
I think the problem must be with cygwin terminal's non-proper support for Unicode. It seems the framework detects that unicode is available, but the terminal doesn't handle it properly.

Try pulling the latest version (https://github.com/niieani/bash-oo-framework/commit/275e7d8bbd08acdd9e983caef768b4a8a7461e48) and change the bootstrap line to:
```
## BOOTSTRAP ##
NO_UNICODE=true source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/lib/oo-framework.sh"
```
The difference is in ```NO_UNICODE=true``` added which will force the framework not to use powerline even if supported.
If that doesn't help, let me know.

**Comment by masavini** [comment]
very same issue on ubuntu 14.04 with GNOME Terminal 3.6.2.
command `stty sane` restores prompt correct behaviour.

bootstrap without UNICODE, instead, does not help.

**Comment by niieani** [comment]
Thanks for reporting. PRs are welcome, since I don't currently have time to try and reproduce this in a VM.

**Comment by masavini** [comment]
@digulla solution works fine for me as well.

just note that line `trap "stty sane; exit 1" INT` should be n. 226 in the current version of `lib/util/exception.sh`.

**Comment by niieani** [comment]
> n. 226

@masavini do you mean line 226?

**Comment by masavini** [comment]
yeap

**Comment by niieani** [comment]
@masavini would you like to send a PR with the correction?
