### ISSUE TITLE
imagemagick name conflict

### ISSUE THREAD

**Issue by ukos-git** [niieani/bash-oo-framework#42]
I need imagemagick for taking screenshots in my current bash project.

I tried to add this framework to it, but `import` does not work for 	`import util/exception`:

```
import-im6.q16: unable to open image `util/exception': No such file or directory @ error/blob.c/OpenBlob/201.
```

import is a native imagemagick function. Is there a way to work around this, i.e. unbind import before sourcing the framework and afterwards binding import again?

```
$ which import
/usr/bin/import
```

**Comment by tterranigma** [comment]
After sourcing Bash Infinity (the `lib/oo-bootstrap.sh` file), you can have:

```sh
unalias "import"
```

You can use the `.` alias to keep using Bash Infinity's import functionality.

**Comment by ukos-git** [comment]
If I understand correctly, I could unalias the import from `lib/oo-bootstrap.sh` right after using `import util/exception`.

But I will have to redirect the import binary from imagemagick in the first place. Because now, if I call import after sourcing the file from `lib/oo-bootstrap.sh`, imagemagick is triggered.

> You can use the . alias to keep using Bash Infinity's import functionality.

I did not get that part.

**Comment by tterranigma** [comment]
`oo-bootstrap.sh` sets three relevant aliases:

```sh
alias import="__oo__allowFileReloading=false System::Import"

alias source="__oo__allowFileReloading=true System::ImportOne"

alias .="__oo__allowFileReloading=true System::ImportOne"
```
The first one can import many files at once, skipping the ones that are already loaded. The other two source a file no matter what. 

After sourcing `oo-bootstrap.sh`, you can: 

```
unalias '.'
alias .="__oo__allowFileReloading=false System::Import"
```
to have '.' do what 'import' did.

You can do this right after sourcing the bootstrap file.

**Comment by ukos-git** [comment]
You pointed me in the right direction:
instead of 
```
import util/exception
```

one can use

```bash
__oo__allowFileReloading=false System::Import util/exception
```

**Comment by tterranigma** [comment]
BTW, this might had been the actual reason for the aliases not working.

**Comment by reuvenpo** [comment]
Wouldn't
```
alias .=$(alias import)
```
or similar, be better than the explicit
```
unalias '.'
alias .="__oo__allowFileReloading=false System::Import"
```
?

Will be more robust and less "leaky" in terms of encapsulation too.
