### ISSUE TITLE
Add an example how to log at different log levels

### ISSUE THREAD

**Issue by digulla** [niieani/bash-oo-framework#5]
I thought this should work:

    namespace app
    Log.AddOutput app DEBUG
    subject=info Log "Done"

but it logs at the defaut level (DEBUG) instead of INFO.

**Comment by niieani** [comment]
```subject``` variable is optional, it gives extra info to the logging function so you can identify and filter out or mark with color certain lines. It gives more flexibility for you than logging levels traditionally do. If you'd like to imitate traditional logging levels you could do the following:

```
namespace app
Log.AddOutput DEBUG DEBUG
Log.AddOutput INFO INFO
Log.AddOutput WARN WARN

subject=DEBUG Log "Debugging"
subject=INFO Log "Done"
subject=WARN Log "Problem!"
```

...and so on. But you can do much more advanced things too, like filter by namespace or even specific function:


```
namespace app

# when logging with subject "test1" inside of namespace app use DEBUG:
Log.AddOutput app/test1 DEBUG
Log.AddOutput INFO INFO
Log.AddOutput WARN WARN

subject=DEBUG Log "Debugging"
subject=INFO Log "Done"
subject=WARN Log "Problem!"
```

**Comment by niieani** [comment]
```subject``` variable is optional, it gives extra info to the logging function so you can identify and filter out or mark with color certain lines. It gives more flexibility for you than logging levels traditionally do. If you'd like to imitate traditional logging levels you could do the following:

```
namespace app
Log.AddOutput DEBUG DEBUG
Log.AddOutput INFO INFO
Log.AddOutput WARN WARN

subject=DEBUG Log "Debugging"
subject=INFO Log "Done"
subject=WARN Log "Problem!"
```

...and so on. But you can do much more advanced things too, like filter by namespace or even specific function:


```
namespace app

# when logging with subject "test1" inside of namespace app use DEBUG:
Log.AddOutput app/test1 DEBUG
Log.AddOutput app/someFunction INFO

# will log "Debugging" to DEBUG
subject=test1 Log "Debugging" 

# will log everything within below function to INFO
someFunction() {
     Log "Done"
}
```

Take a look here for more info:
https://github.com/niieani/bash-oo-framework#advanced-logging

Play around with the tests file ```./tests/logging.sh```:
https://github.com/niieani/bash-oo-framework/blob/master/tests/logging.sh
