### ISSUE TITLE
integrate oo with the modern way using bpkg

### ISSUE THREAD

**Issue by drefixs** [niieani/bash-oo-framework#55]
Hi everyone 😄  

oo is fantastic job in the bash world, I'm very impressed with it.

I would like to help the project add to [bpkg.io](bpkg.io) (Lightweight bash package manager )
may be i can update "how to use readme" adding a way to set up it with bpkg ?

#54

**Comment by niieani** [comment]
Hi @drefixs, thanks for the kind words! I've merged the PR. Feel free to join our effort at building the roadmap for v3.0 https://github.com/niieani/bash-oo-framework/issues/45.

**Comment by niieani** [comment]
Oh, and I'd be open to merging a change regarding "how to use" the bpkg option :)
