### ISSUE TITLE
Debugging lib/system/06_system.sh

### ISSUE THREAD

**Issue by steffenhoenig** [niieani/bash-oo-framework#6]
Hi niieani,

I forked your bash-oo-framework to extend the System.Import function for loading modules directly from github repos. Thus I'd like to print out the **subject=level{2,3,4} ....** lines Unfortunately I don' really understand how to set-up the logger.

I tried this:

```
#!/usr/bin/env bash

## BOOTSTRAP ##
source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/lib/oo-framework.sh"

level_debug(){
  echo "level: $*"
}

Log.RegisterLogger level4 level_debug
Log.RegisterLogger level3 level_debug
Log.RegisterLogger level2 level_debug


## MAIN ##

import lib/steffenhoenig/crash/modules/example
import lib/type-core

```

**Comment by niieani** [comment]
Hey @steffenhoenig. That's a really cool idea! I was thinking of implementing something similar, but never got enough time for it.
Anyway, to the logger. 
Function `Log.RegisterLogger` takes two parameters:
First is the `name of the logger` - how you want to call it. 
Second is the `name of the function that is used for logging`.

After you register the logger in the system, you need to set what you want logged. The simplest way to do that is to log everything in a `namespace`. Just put `namespace Hello` in the file you want to log from and then:
`Log.AddOutput Hello $logger_name`

Take a look here for the example usage: [logging.sh](https://github.com/niieani/bash-oo-framework/blob/master/tests/logging.sh).

In any case, if all you need is to use `subject=$log_level`, you can use the default loggers, which are already registered. Default logger `CUSTOM` prints the `$subject` by default.

```bash
#!/usr/bin/env bash

## BOOTSTRAP ##
source "$( cd "${BASH_SOURCE[0]%/*}" && pwd )/lib/oo-framework.sh"

namespace MyApp
Log.AddOutput MyApp CUSTOM

subject=WARN Log "I am a warning"
subject=STEFFEN Log "I am a Steffen :-)"
```

The above should work and print out:
```
[WARN] [steffen.sh:9] I am a warning 
[STEFFEN] [steffen.sh:10] I am a Steffen :-) 
```

If you don't want the file and line in the logs, we can write a simple Logger Function:
```bash
# (...) bootstrap (...) #

namespace MyApp

SteffensLoggingFunction() {
    Console.WriteStdErr "$(UI.Color.Blue)[$subject]$(UI.Color.Default) $*"
}

Log.RegisterLogger STEFFEN_SHORT_LOGGER SteffensLoggingFunction
Log.AddOutput MyApp STEFFEN_SHORT_LOGGER

subject=WARN Log "I am a warning"
subject=STEFFEN Log "I am a Steffen :-)"
```

Prints:
```
[WARN] I am a warning 
[STEFFEN] I am a Steffen :-) 
```

Be sure to checkout both doc. sections on logging:
* https://github.com/niieani/bash-oo-framework#using-basic-logging-colors-and-powerline-emoji
* https://github.com/niieani/bash-oo-framework#advanced-logging

If you have more questions, shoot.

**Comment by niieani** [comment]
Also, regarding what you're trying to do - I think it would be better if you wrote a new module, say `System.HttpImport` for that purpose. We could integrate it at a later point, but for now - for debugging purposes - it will be much easier for you to develop that way.

**Comment by niieani** [comment]
@steffenhoenig did that help? Can I close the issue?

**Comment by steffenhoenig** [comment]
Hi @niieani ,

yeah that helped to get my head around it. Just working with a line like

```
namespace oo
Log.AddOutput oo CUSTOM
```
And, et voila I got all the debug output I had been after. Thx mate.

P.S. Your hint to make it upstream compatible inspired me to refactor it to another file. Will upload it asap. Cheers!
