### ISSUE TITLE
for people who want to use Bpkg to install this framework

### ISSUE THREAD

**Issue by Cj-bc** [niieani/bash-oo-framework#71]
(This issue is writn for infomation sharing.)

It *doesn't work at this time because of bpkg's bug.*
I find [this issue](https://github.com/bpkg/bpkg/issues/106) in bokg which referred to this problem.
And there's also [PR to fix this](https://github.com/bpkg/bpkg/pull/105) but not mergerd yet.

For now, if you try to install using bpkg, you'll get results like this:
https://asciinema.org/a/208863

What we can do is just to wait for the time PR is merged...

**Comment by Potherca** [comment]
**FYI:** The linked issue https://github.com/bpkg/bpkg/issues/106 and MR #https://github.com/bpkg/bpkg/issues/105 have been merged and closed.

Fix has been release as part of [BPKG v0.3.1](https://github.com/bpkg/bpkg/releases/tag/0.3.1)
