### ISSUE TITLE
Unable to load lib/types/ui/color.sh

### ISSUE THREAD

**Issue by avdv** [niieani/bash-oo-framework#8]
Hi Bazyli,

after you resolved #7, I'm running into another problem:

```
 ✘ UNCAUGHT EXCEPTION: Manually invoked
    ➦ Unable to load /src/bash-oo-framework/lib/types/ui/color.sh [06_system.sh:14]
    ✘ source "$libPath" || throw "Unable to load $libPath" [06_system.sh:14]
       ➦ System.LoadFile "$file" [06_system.sh:66]
          ➦ System.Import [oo.sh:5]
          ✘ import lib/types/ui [oo.sh:5]
```

Thanks.

**Comment by avdv** [comment]
Oh, I see. I'm using urxvt, so my TERM variable is "rxvt".

**Comment by niieani** [comment]
Hi Claudio. 
Still, it shouldn't throw, just make everything black&white. I'll have to investigate further.

**Comment by avdv** [comment]
Adding a `return 0` at the end of lib/types/ui/color.sh works.

**Comment by niieani** [comment]
@avdv Great catch! Thanks.
